PR_TITLE_REGEX: /((?:[a-z][a-z]+))(\d{3})(:)([a-z0-9])/i
COMMIT_MESSAGE_REGEX: /(#)(#)((?:[a-z][a-z]+))(\d{3})(:)([a-z0-9])/i

todo:
  keyword: ["@todo", "TODO"]
  bodyKeyword: ["@body", "BODY"] # string|string[]
  blobLines: 5                # number|boolean, 0 or false to disable
  autoAssign: true            # string|string[]|boolean
  label: true                 # boolean|string|string[]
  reopenClosed: true          # boolean