repos:
- hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
  - args:
    - --branch
    - main
    - --branch
    - develop
    id: no-commit-to-branch
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
- hooks:
  - id: gitlint
  repo: https://github.com/jorisroovers/gitlint
  rev: bf0df47
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.17.4
