package com.iita.akilimo.utils.enums;

public enum EnumFragmentsIdentifiers {
    LOCATION_FRAGMENT,
    AREA_UNITS_FRAGMENT,
    CROPPING_SYSTEM_FRAGMENT,
    CULTIVATION_ADVICE_FRAGMENT,
    FIELD_AREA_FRAGMENT,
    PLANTING_DATE_FRAGMENT,
    HARVEST_DATE_FRAGMENT,
    TRACTOR_FRAGMENT,
    HERBICIDES_FRAGMENT,
    CURRENT_PRACTICE_FRAGMENT,
    OPERATION_COSTS_FRAGMENT,
    CURRENT_FIELD_YIELD_FRAGMENT,
    FERTILIZER_TYPES_FRAGMENT,
    STARCH_FACTORY_FRAGMENT,
    UNIT_OF_SALE_FRAGMENT,
    UNIT_PRICE_FRAGMENT,
    INVESTMENT_FRAGMENT,
    COMPUTE_FRAGMENT,
    MAIZE_PERFORMANCE,
    UNIT_OF_SALE_MAIZE_FRAGMENT
}
