package com.akilimo.mobile.utils.enums

enum class EnumAdviceTasks {
    PLANTING_AND_HARVEST,
    AVAILABLE_FERTILIZERS,
    AVAILABLE_FERTILIZERS_CIS,
    AVAILABLE_FERTILIZERS_CIM,
    INVESTMENT_AMOUNT,
    CURRENT_CASSAVA_YIELD,
    MAIZE_PERFORMANCE,
    MARKET_OUTLET_CASSAVA,
    MARKET_OUTLET_MAIZE,
    MARKET_OUTLET_SWEET_POTATO,
    TILLAGE_OPERATIONS,
    COST_OF_WEED_CONTROL,
    MANUAL_TILLAGE_COST,
    TRACTOR_ACCESS,
    NOT_SELECTED,
    TEST_MARKET_WIZARD
}
