style: github
template: CHANGELOG.tpl.md
info:
  title: AKILIMO CHANGELOG
  repository_url: https://github.com/IITA-AKILIMO/akilimo-mobile
options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
        - docs
        - refactor
        - ci
  commit_groups:
    group_by: Type
    sort_by: Title
    title_order:
      - feat
    title_maps:
      feat: Features
      fix: Bug Fixes
      perf: Performance Improvements
      refactor: Code Refactoring
      doc: Documentation changes
      ci: Continuous integration changes
  header:
    pattern: "^(\\w*)\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
