name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Make gradlew executable
        run: sudo chmod +x ./gradlew
      - name: Run tests
        run: ./gradlew test -x lint