name: build
on: 
  push:

jobs:
  build_artifact:
    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Make gradlew executable
        run: sudo chmod +x ./gradlew
      - name: Generate Release APK
        run: ./gradlew assembleRelease -x test