name: akilimo_build_bot
on:
  push:
    branches:
      - chore/cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Run tests
        run: ./gradlew test