name: GitHub Release

on:
  pull_request:
    branches:
      - main
    types: [closed]
  workflow_dispatch:

jobs:
  release:
    concurrency:
      group: release-${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    if: github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true
    runs-on: ubuntu-24.04
    name: Create release tag
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout commit
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.sha }}

      - name: Fetch tags
        run: git fetch --tags

      - name: Detect relevant changes
        id: diff_check
        uses: tj-actions/changed-files@v47
        with:
          files: |
            **.yml
            **.kt
            **.kts
            **.xml
            **.gradle
            gradlew
            gradlew.bat

      - name: Generate changelog
        if: >
          github.event_name == 'workflow_dispatch' ||
          fromJSON(steps.diff_check.outputs.all_changed_files_count) >= 2
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

#      - name: Commit and push changelog
#        if: >
#          github.event_name == 'workflow_dispatch' ||
#          fromJSON(steps.diff_check.outputs.all_changed_files_count) >= 2
#        uses: stefanzweifel/git-auto-commit-action@v5
#        with:
#          commit_message: "docs: update changelog"
#          file_pattern: CHANGELOG.md
#          commit_user_name: "munywele-sonar[bot]"
#          commit_user_email: "munywele-sonar[bot]@users.noreply.github.com"

      - name: Generate Tag
        if: >
          github.event_name == 'workflow_dispatch' ||
          fromJSON(steps.diff_check.outputs.all_changed_files_count) >= 2
        id: tag_version
        uses: masgeek/github-tag-action@release
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          tag_prefix: ""
          create_annotated_tag: true

      - name: Create GitHub Release
        if: >
          github.event_name == 'workflow_dispatch' ||
          fromJSON(steps.diff_check.outputs.all_changed_files_count) >= 2
        uses: ncipollo/release-action@v1
        with:
          token: ${{ steps.app-token.outputs.token }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Version ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          makeLatest: true
          allowUpdates: true
