name: Next Release PR

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  next_release_pr:
    runs-on: ubuntu-24.04
    name: Next Release PR

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.6.0
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          title: 'Next release'
          reviewer: ${{ github.actor }}
          assignee: ${{ github.actor }}
          target_branch: main
          label: release
          old_string: "**Write you description here**"
          body: "${{ github.event.head_commit.message }}"
          new_string: "${{ github.event.head_commit.message }}"
          get_diff: false
