name: Create next release
on:
  push:
    branches:
      - develop
      - ci/fix-auto-approve
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Next release'
          reviewer: "munywele-bot"
          assignee: ${{ github.actor }}
          target_branch: main
          label: release
          new_string: "** Automatic pull request **"
          body: "** Automatic pull request **"
          get_diff: false
