name: test
on: 
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Make gradlew executable
        run: sudo chmod +x ./gradlew
      - name: Unit tests
        run: ./gradlew test -x lint