name: test
on: 
  push:

jobs:
  run_tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Make gradlew executable
        run: sudo chmod +x ./gradlew
      - name: Unit tests
        run: ./gradlew tasks

  build_artifacts:
    if: contains(github.ref, 'develop') || contains(github.ref, 'master')
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Unit tests
        run: ./gradlew assembleRElease