name: TODO Check

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  todo_check:
    runs-on: ubuntu-24.04
    name: Scan TODOs

    steps:
      - uses: actions/checkout@v4

      - name: Run tdg-github-action
        uses: ribtoks/tdg-github-action@2e71a53c3aae01ab7196b87f3575739462cb507d # v0.4.17
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
          LABEL: "TODO"
          INCLUDE_PATTERN: "\\.(kt|kts)$"
